### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by mikecann** [nightwolfz/mobx-starter#10]
Hi,

Love this starter project, absolutely nails all the essentials in a modern SPA. 

I am however a bit of a Typescript fan so would love to use TS on both the client and server. I dont suppose you know anyone that has had a go at converting this to use Typescript have you before I start?

Cheers,
Mike

**Comment by nightwolfz** [comment]
I have just started learning TypeScript myself and loving it so far!

However I don't know anyone who's done that yet...

**Comment by mikecann** [comment]
Ye I have been using it since the very first beta, it catches so many errors that are easy to make in JS. Use it on most of my web projects.

Unfortunately im not a webpack expert tho so always find it hard when I have to dig too deep into webpack. 

It should just be a matter of using ts-loader then feeding the results into babel.. I think... http://stackoverflow.com/questions/38320220/how-to-setup-typescript-babel-webpack

Im going to have a go at it later this week, hopefully it should just be a matter of converting one file at a time (renaming *.js to *.ts) and working through the typing issues that come up, gonna go for MAX strictness tho to avoid those pesky nulls...

```
{
    "compilerOptions": {
        "outDir": "built",
        "target": "es6",
        "module": "commonjs",
        "moduleResolution": "node",
        "jsx": "react",      
        "declaration": false,
        "removeComments": true,
        "experimentalDecorators": true,
        "sourceMap": true,
        "noImplicitAny": true,
        "noImplicitThis": true,
        "strictNullChecks": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true        
    },
    "exclude": [
        "node_modules",
        "built"
    ]
}
```
