### ISSUE TITLE
Actions?

### ISSUE THREAD

**Issue by mikecann** [nightwolfz/mobx-starter#11]
Hi,

I was just wondering if there was a specific reason why you arent using actions here?

Cheers,
Mike

**Comment by nightwolfz** [comment]
Are you talking about the @action decorator?

If yes, it's because the starter is already quite big and using action decorators are optional.

If you need that extra safety feature, It's super easy to add it yourself in your project. Just prepend it to the methods ;)

**Comment by mikecann** [comment]
Ye im talking about the decorator. 

Ye im using them in my app but its a little bit less nice than I would have liked when you are doing async stuff, I was just wondering if there was a specific reason why you werent using them.

Thanks for clearing that up for me.

Mike
