### ISSUE TITLE
  logger:error ReferenceError: document is not defined

### ISSUE THREAD

**Issue by CodeLuca** [nightwolfz/mobx-starter#12]
Whenever running in production for the first time, or any time for that matter I get this error:
`logger:error ReferenceError: document is not defined`
Halp?

**Comment by CodeLuca** [comment]
@nightwolfz

**Comment by nightwolfz** [comment]
@CodeLuca I couldn't reproduce your issue. I pushed some changes that might fix it...

Otherwise you can checkout the `next` branch. 

It uses koa and react-router v4. Even-though it's not finished, it's a much better setup in my opinion.

**Comment by CodeLuca** [comment]
@nightwolfz really appreciate the commit, everything's working perfectly now, thanks for the project in general as well :)
