### ISSUE TITLE
onEnter not called on client

### ISSUE THREAD

**Issue by omaksi** [nightwolfz/mobx-starter#14]
From what I understood from the readme, onEnter should be isomorphic, but it doesn't seem to be called from the client. RRv4 doesn't call onEnter like v2.

Also, on the server side it seems that preload.js executes all of the onEnter methods.

**Comment by nightwolfz** [comment]
I fixed the SSR part, however for the client side it's pretty difficult at the moment since the history object is not exposed by RRv4. But they are planning to, so as soon as they expose it, I will update the code.

In the meantime, you can call your static methods inside componentDidMount

```
class MyComponent extends Component {
  onEnter() {
    //your code here
  }
  componentDidMount() {
    MyComponent.onEnter();
  }
}
```

**Comment by omaksi** [comment]
Ah, I see. The history object is currently available through context. v4 has a withRouter PR ready that would expose it for components, so I understand you might want to wait until it's merged.

btw. did you push the SSR fix?

**Comment by nightwolfz** [comment]
I wanted to make `withRouter` work with what I have before pushing but looks it'll take longer than expected. I'll push what I have in a few hours.

**Comment by nightwolfz** [comment]
Pushed the fix

**Comment by omaksi** [comment]
I've only just checked it over the weekend and seems working fine, thanks! 
Just a notice, there's still /core/helpers/onEnter which doesn't seem to be used anywhere.

**Comment by nightwolfz** [comment]
@omaksi Thanks, just deleted that file 👍

**Comment by alexmipego** [comment]
Is this on the master branch? It doesn't seem to be called.
