### ISSUE TITLE
npm run prod - Unexpected token <

### ISSUE THREAD

**Issue by JoleMile** [nightwolfz/mobx-starter#15]
Hi,

when I try to run "npm run prod", the app partly renders and shows the next error:
"Uncaught SyntaxError: Unexpected token <"
Im using node v6.9.1 and local mongo is running.
Everything seems to work ok when using the dev script.

One more question is how should i host this on heroku? I just upload the whole project without changing anything?

Thanks in advance.

**Comment by nightwolfz** [comment]
@JoleMile Thanks for reporting! I haven't used Heroku before, so no idea there.

**Comment by nightwolfz** [comment]
@JoleMile Please pull and try again. If the problem persists, could you give me more details. Thanks!

**Comment by xcodebuild** [comment]
Same issue here. `/build/bundle.js(css)` return a 404 page but `build/bundle.js` is a correct js file in fact.

Use `koa-static + koa-mount` instead of `koa-static2` then it works fine.

**Comment by xcodebuild** [comment]
And we need move 
```js
// Serve static files
config.http.static.forEach(staticRoute => {
    logger('app:static')(staticRoute.path)
    app.use(mount(staticRoute.url, serve(staticRoute.path)))
})
```

to the front

```js
app.use(render)
```

**Comment by xcodebuild** [comment]
Send a PR here: https://github.com/nightwolfz/mobx-starter/pull/16
