### ISSUE TITLE
Sth must be wrong

### ISSUE THREAD

**Issue by zorganovic** [nightwolfz/mobx-starter#18]
Hi

After running the project, the home page looks not as pretty as the preview.png

![mobx-starter](https://cloud.githubusercontent.com/assets/17620317/20866211/de63bf5c-ba27-11e6-9037-8acef36c4793.png)

My console looks this way
  app:warn Mobx observer: Using observer to inject stores is deprecated since 4.0. Use `@inject("store1", "store2") @observer ComponentClass` or `inject("store1", "store2")(observer(componentClass))` instead of `@observer(["store1", "store2"]) ComponentClass` +0ms
koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x src/server/server.js:57:5
  app:static /home/vagrant/projects/mobx-starter/build +113ms
koa deprecated Support for generators will been removed in v3. See the documentation for examples of how to convert old middleware https://github.com/koajs/koa/tree/v2.x#old-signature-middleware-v1x src/server/server.js:73:9
  app:start Listening on port 2000 +34ms
  webpack:compiler Running on port 2002 +2ms
         Asset     Size  Chunks             Chunk Names
     bundle.js  2.21 MB       0  [emitted]  bundle
    bundle.css  5.86 kB       0  [emitted]  bundle
 bundle.js.map   2.5 MB       0  [emitted]  bundle
bundle.css.map    17 kB       0  [emitted]  bundle
webpack: bundle is now VALID.

**Comment by zorganovic** [comment]
I have this in the console
GET http://localhost:2002/build/bundle.css net::ERR_SOCKET_NOT_CONNECTED
GET http://localhost:2002/build/bundle.js net::ERR_SOCKET_NOT_CONNECTED

**Comment by zorganovic** [comment]
I was running the prject in a vagrant box and for some reason the 2002 is not forwarded even though I'm configuringit correctly like the 2000 :disappointed:

**Comment by nightwolfz** [comment]
@zorganovic I see, so the problem is solved then?

**Comment by zorganovic** [comment]
@nightwolfz I just found "the" solution to fix it :relieved: 
in webpack.dev.js, line 68, replace localhost by 0.0.0.0
.listen(port, 'localhost', function (err, result) {
.listen(port, '0.0.0.0', function (err, result) {

That's it !! Obviously there's no pb with prod since it doesn't use 2002
By the way, nice starter project dude ! Could you please, write more explanations on how it works bhindthe scene: the helpers, webpack stuff...
