### ISSUE TITLE
About.js component connected

### ISSUE THREAD

**Issue by pixelgrid** [nightwolfz/mobx-starter#2]
The About component is decorated with the @connect decorator, but it has no dynamic content in it.
Nothing changes so no reason to have it decorated. Did i miss something?

**Comment by nightwolfz** [comment]
You should decorate every component, it actually makes the rendering even more efficient.

https://mobxjs.github.io/mobx/best/pitfalls.html

```
Use @observer on all components that render @observable's.

@observer only enhances the component you are decorating, not the components used inside it. So usually all your components should be decorated. Don't worry, this is not inefficient, in contrast, more observer components make rendering more efficient.
```

P.S. @connect is just @observer with a twist.
