### ISSUE TITLE
update README.md

### ISSUE THREAD

**Issue by zorganovic** [nightwolfz/mobx-starter#22]
Hi,

I think that the documetation needs update :
- @connect is no more used
- server.SSR disappeared from the config file
- catcher.js no more used (why?)
by the way enabling catcher prevents the app from starting.
I noticed also that if we try to register a user with special characters in his username the rendered validation message is "Internal Server Error" and not the more precise one written in server/routes/account.js line 52

**Comment by nightwolfz** [comment]
@zorganovic 

I've fixed `catcher.js` and updated the README file a bit.

About SSR, people have told me this starter is more of a Ferrari than a basic app, making it hard to get started for beginners. So I tried to simplify it a bit.

Maybe I should move a lot of the complicated logic into `core` and hide it inside a npm package just like `next.js`.

**Comment by zorganovic** [comment]
Thank you for the quick fix on a saturday night !!!
Better have a Ferrari that one can try to learn how to drive it, than a dull 2CV going no where :wink:
