### ISSUE TITLE
Getting params

### ISSUE THREAD

**Issue by zorganovic** [nightwolfz/mobx-starter#23]
Hi 
I'm missing something about how to get the URL params
Supose we have a route in App.js
`<Match pattern="/page/applicants/enroll/:id" component={EnrollApplicant}/>`
In preload.js we put
`pattern: '/page/applicants/enroll/:id',
 execute: EnrollApplicant.onEnter`

But when I call `console.log(params)` in onEnter I have undefined

I'm suspecting refactoring fetchData to onEnter broke this !

**Comment by nightwolfz** [comment]
@zorganovic  Can you check the latest changes?

Also, if you want the latest and the greatest, I suggest you give [inferno-starter](https://github.com/nightwolfz/inferno-starter) a try :) I usually just backport what I can from that project

**Comment by zorganovic** [comment]
Thanks dude ! it works :tada: 
I'll definitely take a closer look to inferno starter..  Perhaps I'll even try to help porting from it to this project :smile:
