### ISSUE TITLE
graphql server

### ISSUE THREAD

**Issue by sanglnv** [nightwolfz/mobx-starter#24]
Hello there, 
I integrated graphql server and enabled **graphiql** 
Q: How to render **graphiql** query page instead of **NotFound** page when entering **localhost:2000/graphql**? 
Has anyone else integrate it before?

Thanks

**Comment by nightwolfz** [comment]
@sanglnv I don't have experience with `graphql` but I would move **localhost:2000/graphql?** to **localhost:2000/api/graphql?** so it doesn't conflict with other routes.
