### ISSUE TITLE
Hot Module Replacement not working for CSS changes.

### ISSUE THREAD

**Issue by mjyoung** [nightwolfz/mobx-starter#25]
First of all, love this starter pack!

I ran into a small issue -- in dev mode, HMR is working with changes to the JSX but not working with changes to the CSS files. I believe this has to do with the fact that we are using extract-text-webpack-plugin in dev.

Taken from:
https://github.com/webpack/extract-text-webpack-plugin

> Caveats:
> 
> Additional HTTP request
> Longer compilation time
> More complex configuration
> No runtime public path modification
> No Hot Module Replacement

**Comment by nightwolfz** [comment]
@mjyoung Thanks! Unfortunately you're right, you may need to plug something else in to make the browser refresh CSS... I'm sure someone somewhere made a webpack plugin exactly for this purpose :)

**Comment by mjyoung** [comment]
I've opened a PR with a fix for this

**Comment by nightwolfz** [comment]
Cool !
