### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by sxcooler** [nightwolfz/mobx-starter#27]
I just git cloned this repo, and npm i, and npm run dev, then got this:
![image](https://cloud.githubusercontent.com/assets/3192045/23821831/6bc1a970-0679-11e7-893c-58b63d97619b.png)
my node is v7.1.0, npm 3.10.9, during installation there is no error or warning.
I tried install a mongodb, still got this.

**Comment by nightwolfz** [comment]
Try the latest version, many things have changed
