### ISSUE TITLE
spawn cmd ENOENT

### ISSUE THREAD

**Issue by alexbigapps23** [nightwolfz/mobx-starter#29]
Hi how i can modify this error

> mobx-starter@2.0.0 dev C:\Users\l\Desktop\mobx-starter
> cross-env NODE_ENV=development nodemon ./index.js

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\l\\AppData\\Roam                                                                                                                                  ing\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v4.1.2
npm ERR! file cmd
npm ERR! path cmd
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn cmd
npm ERR! mobx-starter@2.0.0 dev: `cross-env NODE_ENV=development nodemon ./index                                                                                                                                  .js`
npm ERR! spawn cmd ENOENT
npm ERR!
npm ERR! Failed at the mobx-starter@2.0.0 dev script 'cross-env NODE_ENV=develop                                                                                                                                  ment nodemon ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobx-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development nodemon ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobx-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobx-starter
npm ERR! There is likely additional logging output above.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\l\\AppData\\Roam                                                                                                                                  ing\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v6.11.0
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! mobx-starter@2.0.0 dev: `cross-env NODE_ENV=development nodemon ./index                                                                                                                                  .js`
npm ERR! Exit status -4058
npm ERR!
npm ERR! Failed at the mobx-starter@2.0.0 dev script 'cross-env NODE_ENV=develop                                                                                                                                  ment nodemon ./index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mobx-starter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development nodemon ./index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mobx-starter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mobx-starter
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                                  stall?
npm WARN Local package.json exists, but node_modules missing, did you mean to in                                                                                                                                  stall?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\l\Desktop\mobx-starter\npm-debug.log

**Comment by nightwolfz** [comment]
Sorry I have no idea. Maybe it's the space in `NODE_ENV=develop ment`.
