### ISSUE TITLE
Question: Working with params

### ISSUE THREAD

**Issue by mxmtsk** [nightwolfz/mobx-starter#3]
Hey
I'm using your starter to dig deeper in mobx and I have a question regarding route params. What I wanna achieve is that some of my routes are prefixed by a city, for example:

/berlin/events

The available cities come from an api request and I need the complete city list a lot of the times, hence why I don't wanna introduce a new request to ask if the specific city exists.

The result looks like this:

``` json
{
  cities: [
  {
    id: 1,
    name: "Berlin",
    country: "Germany",
    default: 1,
    slug: "berlin"
  },
  {
    id: 2,
    name: "Hamburg",
    country: "Germany",
    default: 0,
    slug: "hamburg"
  }
  ]
}
```

What I set up is this route:

``` javascript
            <Route path=":city" getComponent={requireAsync('Cities/Main')}>
                <IndexRoute getComponent={requireAsync('Cities/Landingpage')} />
            </Route>
```

and the fetchData method as well as componendDidMount just like you did in your example for fetching todos. Works fine, all the cities are fetched.

What I want to do now is call and action where it filters the items by slug and sets it as the "active" city. I just don't know where I would call the action ideally.

I hope you understand what I'm trying to achieve

**Comment by nightwolfz** [comment]
Sorry I'm currently on a trip typing on my phone, I'll give you a better reply in a few days.

Call the action in fetchData, you should have access to the store actions and params there.

**Comment by nightwolfz** [comment]
fetchData({ state, store, params })
