### ISSUE TITLE
on branch next menu is not refreshed

### ISSUE THREAD

**Issue by zorganovic** [nightwolfz/mobx-starter#31]
On branch next
Please find below the scenario
1- register test/test
2- logout
3- click on login then type test/test and press the button
the menu is not refreshed : login still visible
press F5 login becomes logout

**Comment by nightwolfz** [comment]
@zorganovic Do you have the same issue on `next-2` branch ?

**Comment by zorganovic** [comment]
@nightwolfz It's worse :-1: 
Testing branch next-2
When I try to register a new user, I have the following stack trace (see attached print screen)
![mobx](https://user-images.githubusercontent.com/17620317/28063243-6dbfccde-6628-11e7-8917-0cbb8bd069d4.png)

Nevertheless the user is registered and logged in : you can see it if you go to localhost:2000
Logout works and login works but if you try to logout again it fails and the user is still logged in !

**Comment by nightwolfz** [comment]
Yeah it's work in progress. Updated the code, should work now.
