### ISSUE TITLE
Websocket error thrown from react-devtools

### ISSUE THREAD

**Issue by bllfrnch** [nightwolfz/mobx-starter#34]
Hi,

I'm seeing an error thrown by React Devtools in the Chrome console on both the master and next-WIP branches when running `npm run dev`:

`WebSocket connection to 'ws://localhost:8097/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

I've confirmed this isn't occurring in other React projects I'm working on, just this one that I cloned from the mobx-starter repo. My version of Chrome was updated today, and my version of react-devtools was reinstalled today as well. Any ideas why this may be happening?

![image](https://user-images.githubusercontent.com/4458825/30233260-56eb7300-94c2-11e7-836a-5758cebeef95.png)

Thanks for the work you've done here!

**Comment by nightwolfz** [comment]
@bllfrnch Removing react-devtools package seems to have fixed it. The devtools still work with the browser extension.

**Comment by bllfrnch** [comment]
Fixed indeed. Thanks very much!
