### ISSUE TITLE
registration and login fail

### ISSUE THREAD

**Issue by stocksp** [nightwolfz/mobx-starter#4]
clone and npm installed with node version v6.2.1  aok
landing page works
attempting to register or login .... not so good.

```
mobx-starter git:(master) npm run dev

> mobx-starter@0.2.0 dev /Users/paul/projects/mobx-starter
> cross-env NODE_ENV=development node ./index.js

[Static] /build - /Users/paul/projects/mobx-starter/build
HTTP Server listening on port 2000
Webpack DEV Server running on port 2002
Mongodb started on port 27017
webpack built 39bb58bee961b7247e0a in 8309ms
Hash: 39bb58bee961b7247e0a
Version: webpack 2.1.0-beta.14
Time: 8309ms
     Asset     Size  Chunks             Chunk Names
 bundle.js  4.75 MB       0  [emitted]  bundle
bundle.css  5.82 kB       0  [emitted]  bundle
Child extract-text-webpack-plugin:

webpack: bundle is now VALID.
Fetching: api/todos
Unhandled rejection ReferenceError: username is not defined
    at /Users/paul/projects/mobx-starter/src/server/routes/account.js:176:82
    at boundThen (/Users/paul/projects/mobx-starter/src/client/components/Home.js:150:25)
    at /Users/paul/projects/mobx-starter/src/server/routes/account.js:172:12
    at Layer.handle [as handle_request] (/Users/paul/projects/mobx-starter/node_modules/express/lib/router/layer.js:95:5)


```

The accounts document IS being created in the db (password is NOT hashed which is not so great).  I'm confused by the  error as it references server/routes/account.js:176:82.   The source file I have only has 74 lines in it so I have no idea where or what the actual problem is that causes the failure.

**Comment by nightwolfz** [comment]
The source maps are not that great when debugging babelified server-side code. 
I'll try to do something about that.

Thanks for mentioning the issue. I updated the code.

**Comment by stocksp** [comment]
The register/login now works (and the password is hashed!).
I can add and delete entries ... if I attempt to delete one of the existing entries:
I get a post error trying to delete an entry I didn't make ...
Thanks a million for this repo!

**Comment by stocksp** [comment]
Yikes,  seems I had an old todos db, from some other project (almost 2 years old) ... I thought all those entries where your seed data ... not!
Project runs great!
sorry for the noise .....
