### ISSUE TITLE
http://localhost:2002/ - Cannot GET /

### ISSUE THREAD

**Issue by omaksi** [nightwolfz/mobx-starter#6]
![mobxstarter2](https://cloud.githubusercontent.com/assets/1312851/18515733/ab5f0be6-7a96-11e6-8be5-9d601aea0713.PNG)
![mobxstarter1](https://cloud.githubusercontent.com/assets/1312851/18515735/ae91413a-7a96-11e6-9bf3-292e871aef31.PNG)

Any tips? Running on Windows. Didn't have any webpack issues before.

**Comment by nightwolfz** [comment]
The webpack (just for development/hot-reloading) hosts the bundles on [http://localhost:2002](http://localhost:2002)

But the website should be visible on [http://localhost:2000](http://localhost:2000/)

Let me know if that works for you!

**Comment by omaksi** [comment]
Ah, I had the impression that the hot reloading version should be on :2002 as :2000 didn't hot reload for me.

It looks like I have the same issue as #7 then. Maybe it's related to the v1/v2beta webpack components, but that's just a guess. Closing this issue, thanks!
